#ifndef OFX_MIDI_CTRL
#define OFX_MIDI_CTRL

enum cMIDI_CTRL_CODE : int
{
	//Ctrl 
	eMC_SPEED_SLIDER = 16
	
	,eMC_B_ALPHA_LEVEL = 0
	,eMC_C_ALPHA_LEVEL = 1
	,eMC_F_ALPHA_LEVEL = 2

	,eMC_COLOR_HUE = 6
	,eMC_COLOR_LIGHT = 7

	,eMC_CTRL_NEXT = 62
	,eMC_CTRL_PREV = 61
	,eMC_CTRL_TRIGGER = 60

	,eMC_SPEED_TAP = 46
	,eMC_MANUAL_BLINK_B = 41
	,eMC_MANUAL_BLINK_W = 45

	//Background trigger
	,eMC_BACKGROUND = 64
	,eMC_ROTATE_TECT
	,eMC_OPEN
	,eMC_NOISE
	,eMC_VIDEO_SET1
	,eMC_VIDEO_SET2
	,eMC_VIDEO_SET3

	//Object trigger
	,eMC_RAIN = 48
	,eMC_METABALL
	,eMC_WAVE
	,eMC_SNAKE
	,eMC_FIREWORK
	,eMC_TEXT_BAR
	,eMC_SCANNER_H
	,eMC_SCANNER_V	

	//Foreground trigger
	,eMC_WATERFALL = 32
	,eMC_CROSS
	,eMC_SIMPLE_BLINK_W	
	,eMC_SIMPLE_BLINK_B
	,eMC_MYO_BLINK
};

static const int cMIDI_MIN_VALUE = 0;
static const int cMIDI_MAX_VALUE = 127;

static const int cMIDI_BTN_RELEASE = 0;
static const int cMIDI_BTN_PRESS = 127;

#endif // !OFX_MIDI_CTRL
