#ifndef _NAME_MANAGER_
#define _NAME_MANAGER_

#include <string>
using namespace std;

#define CREATE_VALUE(NAME) static const string NAME = #NAME;
#define CREATE_VALUE_WITH_VALUE(NAME, VALUE) static const string NAME = VALUE;

namespace NAME_MGR
{
//-------------------------------------------------
//Ballon Canvas Name
//-------------------------------------------------

	CREATE_VALUE(B1_BACKGROUND);
	CREATE_VALUE(B2_ROTATE_RECT);
	CREATE_VALUE(B3_OPEN);
	CREATE_VALUE(B4_NOISE);
	CREATE_VALUE(B5_VIDEO_SET1);
	CREATE_VALUE(B6_VIDEO_SET2);
	CREATE_VALUE(B7_VIDEO_SET3);
	
	CREATE_VALUE(C1_RAIN);
	CREATE_VALUE(C2_METABALL);
	CREATE_VALUE(C3_WAVE);
	CREATE_VALUE(C4_SNAKE);
	CREATE_VALUE(C5_FIREWORK);
	CREATE_VALUE(C6_TEXT_BAR);
	CREATE_VALUE(C7_SCANNER_H);	
	CREATE_VALUE(C8_SCANNER_V);	

	CREATE_VALUE(F1_WATERFALL);
	CREATE_VALUE(F2_CROSS);
	CREATE_VALUE(F3_SIMPLE_BLINK_W);
	CREATE_VALUE(F4_SIMPLE_BLINK_B);
	CREATE_VALUE(F5_MYO_COLOR_BLINK);
};



#endif //_NAME_MANAGER_